"use client";

import { MotionValue, motion } from "framer-motion";
import Image from "next/image";

/**
 * The device.
 *
 * Built in CSS rather than composited from a render, because the hero
 * scales it past 2× at the top of the page where a bitmap would go soft.
 * That means the parts that make a phone read as a phone have to be
 * drawn: a machined band with a polished edge, a black bezel inside it,
 * the side buttons standing proud of the left and right edges, and a
 * Dynamic Island with an actual camera in it.
 *
 * Every dimension is a percentage of the frame, and the root is a query
 * container, so the whole device — buttons, island, the interface inside
 * it — holds its proportions at any size and at any point in the zoom.
 */

/**
 * The machined band. Bright where a light would catch a chamfer.
 *
 * Kept dark on purpose. The hero scales the device past 2.5x, and at
 * that size a band with light stops in it stops reading as a metal edge
 * a few millimetres wide and becomes wide grey stripes painted down the
 * page. The reference's frame is graphite that all but disappears into
 * the black, with the light doing the work of describing its shape.
 */
const BAND =
  "linear-gradient(145deg,#43484d 0%,#1b1e21 9%,#2e3337 22%,#131518 41%,#0f1113 58%,#2f3438 76%,#141619 90%,#3d4247 100%)";

function SideButton({
  className,
  side,
}: {
  className: string;
  side: "left" | "right";
}) {
  return (
    <span
      aria-hidden
      className={`absolute ${className}`}
      style={{
        background:
          side === "left"
            ? "linear-gradient(90deg,#31363a 0%,#1c1f22 55%,#0e1012 100%)"
            : "linear-gradient(270deg,#31363a 0%,#1c1f22 55%,#0e1012 100%)",
        borderRadius:
          side === "left" ? "0.22em 0 0 0.22em" : "0 0.22em 0.22em 0",
      }}
    />
  );
}

/**
 * The light behind the device.
 *
 * Baked to a bitmap — `public/hero-glow.png`, generated by
 * `scripts/build-hero-glow.py` — because that is what the reference
 * does, and not for stylistic reasons: a `filter: blur()` inside a
 * transform-scaled element has to be re-rasterised on every frame of
 * the zoom, which makes the device flicker badly. A bitmap scales as a
 * texture, so it costs nothing and stays perfectly soft.
 *
 * The texture is a horizon, not an outline: one wide, shallow source
 * sitting on the device's top edge, so the shoulders have sky above
 * them and the sides and bottom are unlit. It contains no hard edges
 * anywhere, which is what lets it survive being scaled past 6x — a rim
 * traced against the silhouette upscales into a visible staircase, and
 * a silhouette cut circular will not sit under a CSS corner rounded
 * elliptically, so its edge shows past the frame.
 *
 * The artwork is 512 × 1024 and is laid out against a 168-wide device
 * at its centre, so it is 3.048× the device wide.
 */
const GLOW = "bg-[url('/hero-glow.png')] bg-contain bg-center bg-no-repeat";

export function PhoneGlow({ settle }: { settle?: MotionValue<number> }) {
  return (
    <div aria-hidden className="pointer-events-none absolute inset-0">
      {/*
        Mobile lights the device, not the sky behind it.

        The reference switches lighting model at its phone breakpoint,
        and it has to: there is no room above the device for a horizon,
        and the device fills most of the width, so a bloom behind it
        would just be a bright smear along the top edge. It edge-lights
        instead — a rim down both sides, biased towards the top, with
        the device sitting in front of it.

        A rim is safe here and nowhere else: mobile drops the zoom
        entirely (`geom.zoom` is 1), so this never gets scaled up and
        cannot stair-step the way a baked rim in the texture did.

        Sized against --phone-w so it holds at any width.
      */}
      <div
        className="absolute inset-0 rounded-[13%/6%] md:hidden"
        style={{
          boxShadow: [
            /* the hot line right on the edge */
            `0 0 calc(var(--phone-w) * 0.022) calc(var(--phone-w) * 0.002) rgba(153,246,228,0.62)`,
            /* the near bloom, biased up so the shoulders are brightest */
            `0 calc(var(--phone-w) * -0.018) calc(var(--phone-w) * 0.1) calc(var(--phone-w) * -0.01) rgba(45,212,191,0.62)`,
            /* the throw */
            `0 calc(var(--phone-w) * -0.02) calc(var(--phone-w) * 0.28) 0 rgba(20,184,166,0.34)`,
            `0 0 calc(var(--phone-w) * 0.62) 0 rgba(13,148,136,0.18)`,
          ].join(","),
        }}
      />

      {/* The far throw of the horizon, desktop only. */}
      <motion.div
        style={{ opacity: settle ?? 1 }}
        className="absolute left-[-120%] top-[-16%] hidden h-[32%] w-[340%] rounded-[50%] bg-[radial-gradient(closest-side,rgba(45,212,191,0.09),rgba(13,148,136,0.03)_44%,transparent_74%)] md:block"
      />
      {/* The horizon itself, desktop only. */}
      <div
        className={`absolute left-1/2 top-1/2 hidden aspect-[512/1024] w-[304.8%] -translate-x-1/2 -translate-y-1/2 md:block ${GLOW}`}
      />
    </div>
  );
}

export function PhoneFrame({
  className = "",
  overlay,
  children,
}: {
  className?: string;
  /**
   * Rendered in the frame's coordinate space but outside the clipped
   * screen, so a card can be placed against the interface behind it and
   * still break past the bezel.
   */
  overlay?: React.ReactNode;
  children?: React.ReactNode;
}) {
  return (
    <div
      className={`relative aspect-[9/19.5] w-full [container-type:inline-size] ${className}`}
    >
      {/* Buttons first, so they sit under the band and read as proud of
          it rather than stuck on top. Left: action, volume up, volume
          down. Right: side button. */}
      <SideButton side="left" className="left-[-1.1%] top-[15.5%] h-[3.6%] w-[1.3%]" />
      <SideButton side="left" className="left-[-1.1%] top-[22.5%] h-[6.4%] w-[1.3%]" />
      <SideButton side="left" className="left-[-1.1%] top-[30.5%] h-[6.4%] w-[1.3%]" />
      <SideButton side="right" className="right-[-1.1%] top-[25%] h-[10%] w-[1.3%]" />

      {/* The band. */}
      <div
        className="absolute inset-0 rounded-[13%/6%] p-[2.1%]"
        style={{
          background: BAND,
          boxShadow:
            "0 0 0 0.09cqw rgba(255,255,255,0.11), 0 3cqw 6cqw -1cqw rgba(0,0,0,0.9)",
        }}
      >
        {/* Black bezel between the band and the glass. */}
        <div className="h-full w-full rounded-[11.4%/5.3%] bg-[#050505] p-[1.4%]">
          <div className="relative h-full w-full overflow-hidden rounded-[10.2%/4.8%] bg-black">
            {children}
          </div>
        </div>
      </div>

      {/* The chamfer: a bright hairline that runs the outer edge, hottest
          top-left where the key light is. */}
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 rounded-[13%/6%]"
        style={{
          padding: "0.12cqw",
          background:
            "linear-gradient(150deg,rgba(255,255,255,0.34),rgba(255,255,255,0.03) 28%,rgba(255,255,255,0) 58%,rgba(255,255,255,0.12) 100%)",
          WebkitMask:
            "linear-gradient(#000 0 0) content-box, linear-gradient(#000 0 0)",
          WebkitMaskComposite: "xor",
          maskComposite: "exclude",
        }}
      />

      <DynamicIsland />

      {overlay}
    </div>
  );
}

/**
 * The island at rest: the pill, with the front camera in it.
 */
export function DynamicIsland({ className = "" }: { className?: string }) {
  return (
    <div
      aria-hidden
      className={`pointer-events-none absolute left-1/2 top-[3.6%] flex h-[3.1%] w-[27%] -translate-x-1/2 items-center justify-end rounded-full bg-black pr-[2.2cqw] ${className}`}
    >
      <CameraLens />
    </div>
  );
}

export function CameraLens() {
  return (
    <span
      className="block h-[1.9cqw] w-[1.9cqw] rounded-full"
      style={{
        background:
          "radial-gradient(circle at 36% 32%, #3a4f6b 0%, #16202e 46%, #05080d 100%)",
        boxShadow: "inset 0 0 0 0.15cqw rgba(120,150,190,0.35)",
      }}
    >
      <span
        className="ml-[0.35cqw] mt-[0.3cqw] block h-[0.45cqw] w-[0.45cqw] rounded-full"
        style={{ background: "rgba(180,210,255,0.9)" }}
      />
    </span>
  );
}

/**
 * One screenshot inside the frame, for the sections that show real
 * captures rather than the running interface.
 */
export function PhoneScreen({
  src,
  alt,
  preload = false,
  className = "",
}: {
  src: string;
  alt: string;
  preload?: boolean;
  className?: string;
}) {
  return (
    <Image
      src={src}
      alt={alt}
      fill
      sizes="(max-width: 640px) 90vw, 420px"
      quality={88}
      {...(preload ? { preload: true } : { loading: "eager" as const })}
      className={`object-cover object-top ${className}`}
    />
  );
}
